services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true

      KC_DB: postgres
      KC_DB_URL_HOST: db_kc_postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 1234
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloak

    depends_on:
      - db_kc_postgres

    command:
      - start-dev
    ports:
      - "8080:8080"

  db_kc_postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  db_postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d


volumes:
  postgres_data:








